### ISSUE TITLE
Meta: to style

### ISSUE THREAD

**Issue by jlyon** [albatrossdigital/helm#61]
- [ ]  http://dev-helm-civic.pantheon.io/events
- [ ]  http://dev-helm-civic.pantheon.io/calendar
- [ ] http://dev-helm-civic.pantheon.io/documents
- [x] http://dev-helm-civic.pantheon.io/news - what to do abt R sidebar
