### ISSUE TITLE
Helm marketing todo

### ISSUE THREAD

**Issue by jlyon** [albatrossdigital/helm#68]
- [ ] Scroll to top when you click on a page
- [ ] Make responsive
- [ ] Update MyTown/Explore imgs + screenshots
- [x] Fix bullet formatting (MyTown)
- [ ] MyTown demo not working
- [ ] Google analytics
- [ ] Update page title
- [ ] Submit to Google 
- [ ] Adjust padding, etc
- [x] Make top buttons look like MyTown 
- [ ] Get spin up button working
- [ ] write blog post
- [x] get hello@helmcivic.com email working
- [x] add subscribe box
- [ ] https://basecamp.com/2065491/projects/8322825/todolists/27515973
